setup_tasks:
  - createdb abacash-test
  - npm install -g yarnpkg
  - yarn

tasks:
  - PG_URL='postgres://root@localhost/abacash-test' yarn test -- --timeout 0
  - yarn run lint

services:
  - postgresql
